### ISSUE TITLE
Simplify CSS code further for all shared properties.

### ISSUE THREAD

**Issue by josephtkim** [TechieBuddy/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. 

Here's how the simplified code might look like

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}

h1 {
  font-size: 100px;
  color: khaki;
  text-align: center;
}

h2 {
  font-size: 32px;
  color: white;
}

.brushes h2 {
  background-color: mediumspringgreen;
}

.frames h2 {
  background-color: lightcoral;
}

.paint h2 {
  background-color: skyblue;
}

.patternimage {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

.price {
  color: blue;
}
```
